const mongoose = require('mongoose');

/**
 * Schéma Session (session d'étude)
 */
const sessionSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  subjectId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Subject',
    required: true
  },
  title: {
    type: String,
    trim: true,
    maxlength: 200
  },
  date: {
    type: Date,
    required: true,
    index: true
  },
  startTime: {
    type: String,
    required: true,
    match: [/^([01]\d|2[0-3]):([0-5]\d)$/, 'Format HH:MM requis']
  },
  endTime: {
    type: String,
    required: true,
    match: [/^([01]\d|2[0-3]):([0-5]\d)$/, 'Format HH:MM requis']
  },
  duration: {
    type: Number,
    required: true,
    min: 15
  },
  status: {
    type: String,
    enum: ['planned', 'in_progress', 'completed', 'missed', 'cancelled'],
    default: 'planned',
    index: true
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  isGroupSession: {
    type: Boolean,
    default: false
  },
  groupId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Group',
    default: null
  },
  notes: {
    type: String,
    maxlength: 1000,
    default: ''
  },
  actualDuration: {
    type: Number,
    default: 0
  }
}, {
  timestamps: true
});

sessionSchema.index({ userId: 1, date: 1 });
sessionSchema.index({ userId: 1, status: 1 });

module.exports = mongoose.model('Session', sessionSchema);