const Subject = require('../models/Subject');
const Session = require('../models/Session');
const User = require('../models/User');

/**
 * Convertir HH:MM en minutes
 */
const timeToMinutes = (time) => {
  const [hours, minutes] = time.split(':').map(Number);
  return hours * 60 + minutes;
};

/**
 * Convertir minutes en HH:MM
 */
const minutesToTime = (minutes) => {
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return `${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}`;
};

/**
 * Mapping jour → numéro (0=dimanche, 1=lundi, ...)
 */
const DAY_NAME_TO_NUMBER = {
  sunday: 0,
  monday: 1,
  tuesday: 2,
  wednesday: 3,
  thursday: 4,
  friday: 5,
  saturday: 6
};

/**
 * Trouver la prochaine date pour un jour de la semaine donné
 * À partir d'une date de référence
 */
const getNextDateForDay = (refDate, dayName) => {
  const targetDay = DAY_NAME_TO_NUMBER[dayName];
  const date = new Date(refDate);
  const currentDay = date.getDay();
  
  let daysToAdd = (targetDay - currentDay + 7) % 7;
  date.setDate(date.getDate() + daysToAdd);
  
  return date;
};

/**
 * Vérifier si 2 créneaux se chevauchent
 */
const hasOverlap = (slot1Start, slot1End, slot2Start, slot2End) => {
  return slot1Start < slot2End && slot2Start < slot1End;
};

/**
 * 🧠 ALGORITHME PRINCIPAL DE GÉNÉRATION DU PLANNING
 * 
 * @param {String} userId - ID de l'utilisateur
 * @param {Date} startDate - Date de début (par défaut : aujourd'hui)
 * @param {Number} numberOfWeeks - Nombre de semaines à planifier (défaut: 1)
 * @param {Boolean} clearExisting - Effacer les sessions auto-générées existantes
 */
const generatePlanning = async (userId, startDate = new Date(), numberOfWeeks = 1, clearExisting = false) => {
  // ÉTAPE 1 : Récupérer les données
  const user = await User.findById(userId);
  
  if (!user || !user.availability || user.availability.length === 0) {
    throw new Error('Vous devez d\'abord définir vos disponibilités');
  }

  const subjects = await Subject.find({ userId }).sort({ priority: -1 });

  if (subjects.length === 0) {
    throw new Error('Vous devez d\'abord créer au moins une matière');
  }

  // ÉTAPE 2 : Optionnellement, effacer les anciennes sessions auto-générées
  if (clearExisting) {
    const endDateClear = new Date(startDate);
    endDateClear.setDate(endDateClear.getDate() + (numberOfWeeks * 7));
    
    await Session.deleteMany({
      userId,
      isAutoGenerated: true,
      date: { $gte: startDate, $lte: endDateClear },
      status: 'planned'  // Ne pas supprimer celles déjà complétées
    });
  }

  // ÉTAPE 3 : Récupérer les sessions existantes pour vérifier les chevauchements
  const endDate = new Date(startDate);
  endDate.setDate(endDate.getDate() + (numberOfWeeks * 7));
  
  const existingSessions = await Session.find({
    userId,
    date: { $gte: startDate, $lte: endDate },
    status: { $ne: 'cancelled' }
  });

  // ÉTAPE 4 : Préparer les "budgets d'heures" pour chaque matière
  // Pour chaque semaine, chaque matière a son objectif weeklyGoalHours en minutes
  const subjectBudgets = subjects.map(s => ({
    subject: s,
    remainingMinutes: s.weeklyGoalHours * 60 * numberOfWeeks,
    weeklyMinutes: s.weeklyGoalHours * 60
  }));

  // ÉTAPE 5 : Pour chaque semaine, pour chaque jour de dispo, créer des sessions
  const generatedSessions = [];

  for (let week = 0; week < numberOfWeeks; week++) {
    // Reset budget hebdomadaire
    if (week > 0) {
      subjectBudgets.forEach(b => {
        b.remainingMinutes += b.weeklyMinutes;
      });
    }

    // Pour chaque créneau de disponibilité
    for (const availability of user.availability) {
      const sessionDate = getNextDateForDay(startDate, availability.day);
      // Ajouter le décalage de la semaine
      sessionDate.setDate(sessionDate.getDate() + (week * 7));

      // Si la date est dans le passé, sauter
      if (sessionDate < new Date(new Date().setHours(0, 0, 0, 0))) {
        continue;
      }

      const slotStart = timeToMinutes(availability.startTime);
      const slotEnd = timeToMinutes(availability.endTime);
      let currentTime = slotStart;

      // Récupérer les sessions du jour pour vérifier les chevauchements
      const sameDateSessions = existingSessions.filter(s => 
        new Date(s.date).toDateString() === sessionDate.toDateString()
      );

      // Tant qu'il reste de la place dans le créneau
      while (currentTime < slotEnd) {
        // Trouver la matière prioritaire qui a encore besoin d'heures
        const sortedBudgets = [...subjectBudgets]
          .filter(b => b.remainingMinutes > 0)
          .sort((a, b) => {
            // Trier par priorité, puis par heures restantes
            if (b.subject.priority !== a.subject.priority) {
              return b.subject.priority - a.subject.priority;
            }
            return b.remainingMinutes - a.remainingMinutes;
          });

        if (sortedBudgets.length === 0) {
          break; // Toutes les matières ont leurs heures
        }

        const budget = sortedBudgets[0];
        const subject = budget.subject;

        // Calculer la durée de la session
        const remainingInSlot = slotEnd - currentTime;
        const sessionDuration = Math.min(
          subject.maxSessionDuration,    // Max selon la matière
          budget.remainingMinutes,       // Ce qu'il reste à étudier
          remainingInSlot,               // Espace restant dans le créneau
          120                            // Max global 2h
        );

        // Si moins de 30min, passer
        if (sessionDuration < 30) {
          break;
        }

        const sessionEnd = currentTime + sessionDuration;

        // Vérifier les chevauchements avec sessions existantes
        const overlap = sameDateSessions.find(s => 
          hasOverlap(currentTime, sessionEnd, timeToMinutes(s.startTime), timeToMinutes(s.endTime))
        );

        if (overlap) {
          // Sauter la session existante
          currentTime = timeToMinutes(overlap.endTime);
          continue;
        }

        // ✅ Créer la session
        const newSession = await Session.create({
          userId,
          subjectId: subject._id,
          title: `🤖 ${subject.name}`,
          date: new Date(sessionDate),
          startTime: minutesToTime(currentTime),
          endTime: minutesToTime(sessionEnd),
          duration: sessionDuration,
          status: 'planned',
          isAutoGenerated: true,
          notes: 'Session générée automatiquement'
        });

        await newSession.populate('subjectId', 'name color priority');
        generatedSessions.push(newSession);

        // Décrémenter le budget
        budget.remainingMinutes -= sessionDuration;

        // Avancer dans le créneau (avec une pause de 15min entre sessions)
        currentTime = sessionEnd + 15;
      }
    }
  }

  return {
    success: true,
    sessionsCreated: generatedSessions.length,
    sessions: generatedSessions,
    summary: {
      totalSubjects: subjects.length,
      totalAvailabilitySlots: user.availability.length,
      weeksPlanned: numberOfWeeks,
      remainingByPriority: subjectBudgets.map(b => ({
        subject: b.subject.name,
        priority: b.subject.priority,
        weeklyGoalHours: b.subject.weeklyGoalHours,
        remainingMinutes: b.remainingMinutes,
        achieved: ((b.weeklyMinutes * numberOfWeeks - b.remainingMinutes) / (b.weeklyMinutes * numberOfWeeks)) * 100
      }))
    }
  };
};

/**
 * Analyser la faisabilité du planning AVANT de générer
 */
const analyzePlanning = async (userId) => {
  const user = await User.findById(userId);
  const subjects = await Subject.find({ userId });

  if (!user) {
    throw new Error('Utilisateur non trouvé');
  }

  // Calculer le total d'heures disponibles par semaine
  let totalAvailableMinutes = 0;
  user.availability.forEach(slot => {
    totalAvailableMinutes += timeToMinutes(slot.endTime) - timeToMinutes(slot.startTime);
  });

  // Calculer le total d'heures nécessaires
  let totalNeededMinutes = 0;
  subjects.forEach(s => {
    totalNeededMinutes += s.weeklyGoalHours * 60;
  });

  return {
    success: true,
    analysis: {
      hasSubjects: subjects.length > 0,
      hasAvailability: user.availability.length > 0,
      totalSubjects: subjects.length,
      totalAvailabilitySlots: user.availability.length,
      availableMinutesPerWeek: totalAvailableMinutes,
      availableHoursPerWeek: Math.round(totalAvailableMinutes / 60 * 10) / 10,
      neededMinutesPerWeek: totalNeededMinutes,
      neededHoursPerWeek: Math.round(totalNeededMinutes / 60 * 10) / 10,
      isFeasible: totalAvailableMinutes >= totalNeededMinutes,
      coveragePercentage: totalNeededMinutes > 0 
        ? Math.round((totalAvailableMinutes / totalNeededMinutes) * 100)
        : 0,
      subjects: subjects.map(s => ({
        name: s.name,
        priority: s.priority,
        weeklyGoalHours: s.weeklyGoalHours,
        color: s.color
      }))
    }
  };
};

module.exports = {
  generatePlanning,
  analyzePlanning
};