import { Subject } from './subject.model';

export type SessionStatus = 'planned' | 'in_progress' | 'completed' | 'missed' | 'cancelled';

export interface Session {
  _id: string;
  userId: string;
  subjectId: Subject | string;
  title?: string;
  date: string | Date;
  startTime: string;
  endTime: string;
  duration: number;
  status: SessionStatus;
  isAutoGenerated: boolean;
  isGroupSession: boolean;
  groupId?: string;
  notes?: string;
  actualDuration?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface SessionListResponse {
  success: boolean;
  count: number;
  sessions: Session[];
}

export interface SessionResponse {
  success: boolean;
  message?: string;
  session: Session;
}

export interface CreateSessionRequest {
  subjectId: string;
  title?: string;
  date: string;
  startTime: string;
  endTime: string;
  notes?: string;
}

export interface SessionsStats {
  success: boolean;
  stats: {
    total: number;
    planned: number;
    completed: number;
    missed: number;
    totalMinutes: number;
    totalHours: number;
    completionRate: number;
  };
}

// 🆕 AJOUTS POUR L'ALGORITHME

export interface PlanningAnalysis {
  success: boolean;
  analysis: {
    hasSubjects: boolean;
    hasAvailability: boolean;
    totalSubjects: number;
    totalAvailabilitySlots: number;
    availableMinutesPerWeek: number;
    availableHoursPerWeek: number;
    neededMinutesPerWeek: number;
    neededHoursPerWeek: number;
    isFeasible: boolean;
    coveragePercentage: number;
    subjects: {
      name: string;
      priority: number;
      weeklyGoalHours: number;
      color: string;
    }[];
  };
}

export interface GeneratePlanningRequest {
  startDate?: string;
  numberOfWeeks?: number;
  clearExisting?: boolean;
}

export interface GeneratePlanningResponse {
  success: boolean;
  message: string;
  sessionsCreated: number;
  sessions: Session[];
  summary: {
    totalSubjects: number;
    totalAvailabilitySlots: number;
    weeksPlanned: number;
    remainingByPriority: {
      subject: string;
      priority: number;
      weeklyGoalHours: number;
      remainingMinutes: number;
      achieved: number;
    }[];
  };
}

// Helpers
export const STATUS_LABELS: Record<SessionStatus, string> = {
  planned: '📋 Planifiée',
  in_progress: '⏳ En cours',
  completed: '✅ Complétée',
  missed: '❌ Manquée',
  cancelled: '🚫 Annulée'
};

export const STATUS_COLORS: Record<SessionStatus, string> = {
  planned: 'bg-blue-100 text-blue-700',
  in_progress: 'bg-yellow-100 text-yellow-700',
  completed: 'bg-green-100 text-green-700',
  missed: 'bg-red-100 text-red-700',
  cancelled: 'bg-gray-100 text-gray-700'
};